#!/bin/bash
echo "Updating Database"
RAILS_ENV=production rails db:seed
RAILS_ENV=production rails db:seed:seeds1510
RAILS_ENV=production rails db:seed:neutrino_seeds_amon
RAILS_ENV=production rails db:seed:neutrino_seeds_gcn
RAILS_ENV=production rails db:seed:atca_seeds

