#!/bin/bash
echo "Updating Database"
rails -e production db:seed
rails -e production db:seed:seeds1510
rails -e production db:seed:neutrino_seeds_amon
rails -e production db:seed:neutrino_seeds_gcn
rails -e production db:seed:atca_seeds

